spring:
  application:
    name: lab08-spring-boot-rest
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    open-in-view: false
  data:
    web:
      pageable:
        serialization-mode: via-dto
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/internetMailing?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:
    hikari:
      minimum-idle: 1
      connection-timeout: 60000
      pool-name: SystemPool
      leak-detection-threshold: 10000
      idle-timeout: 120000
    type: com.zaxxer.hikari.HikariDataSource
# logging:
#   level:
#     root: INFO
#     org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: DEBUG
#     liquibase: DEBUG
